version: '3.3'
services:
  postgres:
    image: library/postgres:14-alpine
    restart: always
    environment:
#      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    ports:
      - 5432:5432
