version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "clean-vertical"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-asu1d1zidmos"
s3_prefix = "clean-vertical"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"

