// Code generated by "stringer -type=activityTyp"; DO NOT EDIT.

package dispatch

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EndA-0]
	_ = x[InvokeA-1]
	_ = x[CondA-2]
	_ = x[EffectA-3]
}

const _activityTyp_name = "EndAInvokeACondAEffectA"

var _activityTyp_index = [...]uint8{0, 4, 11, 16, 23}

func (i activityTyp) String() string {
	if i >= activityTyp(len(_activityTyp_index)-1) {
		return "activityTyp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _activityTyp_name[_activityTyp_index[i]:_activityTyp_index[i+1]]
}
