version: '3.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2-arm64
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9600:9600
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2-arm64
    restart: always
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 5601:5601