name: CI
on: [ pull_request ]

jobs:
  test-go:
    name: Test implementation in Golang
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - run: cd comsim; go get -v -t -d ./...
      - run: cd comsim; go generate ./...
      - run: cd comsim; go test -v ./...
      - run: cd clean-vertical; go get -v -t -d ./...
      - run: cd clean-vertical; go test -v ./...
      - run: cd eventsourcing; go get -v -t -d ./...
      - run: cd eventsourcing; go test -v ./...
      - run: cd churchencoding; go get -v -t -d ./...
      - run: cd churchencoding; go test -v ./...
      - run: cd continuations; go get -v -t -d ./...
      - run: cd continuations; go test -v ./...

  test-cdk:
    name: Test infrastructure in CDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true

      - run: cd clean-vertical/distraction/infrastructure/aws-native; npm install
      - run: cd clean-vertical/distraction/infrastructure/aws-native; npm run cdk synth

  finally:
    name: Post-workflow action
    runs-on: ubuntu-latest
    needs:
      - test-go
      - test-cdk
    steps:
      - uses: actions/github-script@v3
#        if: ${{ success() }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '✅ tests are passing'
            })

# Not working, because success depends on previous stage form this job.
#      - uses: actions/github-script@v3
#        if: ${{ failure() }}
#        with:
#          github-token: ${{secrets.GITHUB_TOKEN}}
#          script: |
#            github.issues.createComment({
#              issue_number: context.issue.number,
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              body: '⛔️ tests are failing'
#            })
