name: SDK
on: [ pull_request ]

jobs:
  generate-go:
    name: Generate Golang SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12'
          check-latest: true

      - run: |
          npx @openapitools/openapi-generator-cli generate \
          -i clean-vertical/distraction/infrastructure/aws-native/openapi.yaml \
          -o clean-vertical/distraction/artifacts/gorestsdk \
          -g go \
          --package-name gorestsdk

      - name: Commit generated SDKs
        run: |
          echo ${{ github.ref }}
          git add clean-vertical/distraction/artifacts/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "CI: Automated SDK generation push" -a | exit 0

  generate-js:
    name: Generate JS SDK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@octocat'

      - run: |
          npx @openapitools/openapi-generator-cli generate \
          -i clean-vertical/distraction/infrastructure/aws-native/openapi.yaml \
          -o clean-vertical/distraction/artifacts/jssdk \
          -g javascript

#      - run: cp $NPM_CONFIG_USERCONFIG clean-vertical/distraction/artifacts/jssdk/.npmrc
#      - run: cd clean-vertical/distraction/artifacts/jssdk/; ls -lah
#      - run: cd clean-vertical/distraction/artifacts/jssdk/; cat package.json
      - run: cd clean-vertical/distraction/artifacts/jssdk; npm install
#      - run: cd clean-vertical/distraction/artifacts/jssdk; npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  finally:
    name: Post-generation SDK action
    runs-on: ubuntu-latest
    needs:
      - generate-go
      - generate-js
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '📦 SDKs were generated, not PUBLISHED yet'
            })
